Fix typos and add Event examples
TATUMGAMES/TG-MIKROS-SDK-unity-package pull request #10
Opened 2022-02-24 03:28 UTC by Velite12

### What Does This PR Do?

Fix typos and add Preset/Custom Event examples

2022-02-24 03:32 UTC, drxeno02 commented
@Velite12 Be sure to add everyone for PR review, otherwise they will not be notified and also won't be able to review your PR. I have done this for you this time. Just remember for next time, thanks!

2022-02-24 03:33 UTC, drxeno02 commented on README.md
> +* [How Does MIKROS Work?](#how-does-mikros-work)
👍

2022-02-24 03:34 UTC, drxeno02 commented on README.md
> +<a name="how-does-mikros-work"></a>
💯

2022-02-24 03:34 UTC, drxeno02 commented on README.md
> +## Sample App & Documentation
👍

2022-02-24 03:37 UTC, Velite12 commented
@drxeno02 I think editing the title without reloading the page must have changed the reviewers, it also removed the assignees.

2022-02-24 03:37 UTC, drxeno02 commented on README.md
> +![MIKROS MAIN SCREEN, add from Git URL dropdown](Documentation/Mikros-main-screen.png)
@Velite12 always user lowercasing for images. Rename the image Mikros-main-screen.png -> `mikros_main_screen.png` and update references. Do the same for all images e.g. Mikros-sign-in.png -> `mikros_signin.png` | Mikros-sign-up.png -> `mikros_signup.png` | Mikros-sign-out.png -> `mikros_signout.png` 

Note: In code we treat signin, signup, signout as one word. In business language we use two. It is a matter of convenience.

2022-02-24 03:39 UTC, drxeno02 requested changes
This is a decent start. I have made some suggestions. There are more things that need to be updated, but I can do it myself. This gets us 90% there, which is good.

2022-03-05 16:22 UTC, drxeno02 approved these changes

2022-07-11 05:46 UTC, closed without merging

2022-07-11 05:46 UTC, Debadri-Redapple commented
Closing due to outdated changes.